### GET DE TODOS LOS PRODUCTOS
GET http://localhost:3000/api/v1/products

### GET PARA UN PRODUCTO EN PARTICULAR
GET http://localhost:3000/api/v1/products/f557c5f1-2dab-41df-aa0b-baca1bc8b89f

### GET PARA TRAER TODAS LOS USUARIOS
GET http://localhost:3000/api/v1/users

### GET PARA BUSCAR SOLO UN USUARIO
GET http://localhost:3000/api/v1/users/1

### POST CREAR UN USUARIO
POST http://localhost:3000/api/v1/users
content-type: application/json

{
  "email":"admin4@gmail.com",
  "password": "qwerty123.*",
  "role":"Admin"
}

### PATCH. ACTUALIZAR UN USUARIO
PATCH http://localhost:3000/api/v1/users/1
content-type: application/json

{
  "email":"administrador@gmail.com"
}

### DELETE. ELIMINAR UN USUARIO
DELETE http://localhost:3000/api/v1/users/3


### POST CREAR UN CUSTOMER
POST http://localhost:3000/api/v1/customers
content-type: application/json

{
  "name":"Ariel",
  "lastName":"Mañán",
  "phone":"+569 9772 2031",
  "userId":2
}

### POST CREAR UN CUSTOMER CON EL USUARIO
POST http://localhost:3000/api/v1/customers
content-type: application/json

{
  "name":"Zacha",
  "lastName":"Colipán",
  "phone":"+569 2312 2111",
  "user":{
    "email":"z.colipan@gmail.com",
    "password":"123456"
  }
}

### GET PARA TRAER TODAS LOS CUSTOMERS
GET http://localhost:3000/api/v1/customers

### GET PARA TRAER UN CUSTOMER ESPECIFICO
GET http://localhost:3000/api/v1/customers/1

### GET PARA OBTENER TODAS LAS CATEGORIAS
GET http://localhost:3000/api/v1/categories

### GET PARA OBTENER UNA CATEGORIA POR ID
GET http://localhost:3000/api/v1/categories/3

### POST CREA UNA CATEGORIA
POST http://localhost:3000/api/v1/categories
content-type: application/json

{
  "name":"Animals",
  "image": "https://i.pinimg.com/736x/16/65/97/166597a7616100c943ffad09a1f5b9fc.jpg"
}


### PATCH ACTUALIZAR UNA CATEGORIA
PATCH http://localhost:3000/api/v1/categories/2
content-type: application/json

{
  "name":"Foods",
  "image": "https://i.pinimg.com/736x/16/65/97/166597a7616100c943ffad09a1f5b9fc.jpg"
}

### DELETE PARA ELIMINAR UNA CATEGORIA POR ID
DELETE http://localhost:3000/api/v1/categories/5

