### GET DE TODOS LOS PRODUCTOS
GET http://localhost:3000/api/v1/products

### GET PARA UN PRODUCTO EN PARTICULAR
GET http://localhost:3000/api/v1/products/f557c5f1-2dab-41df-aa0b-baca1bc8b89f

### GET PARA TRAER TODAS LAS TAREAS
GET http://localhost:3000/api/v1/users


### GET PARA OBTENER TODAS LAS CATEGORIAS
GET http://localhost:3000/api/v1/categories

### GET PARA OBTENER UNA CATEGORIA POR ID
GET http://localhost:3000/api/v1/categories/3

### POST CREA UNA CATEGORIA
POST http://localhost:3000/api/v1/categories
content-type: application/json

{
  "name":"Animals",
  "image": "https://i.pinimg.com/736x/16/65/97/166597a7616100c943ffad09a1f5b9fc.jpg"
}


### PATCH ACTUALIZAR UNA CATEGORIA
PATCH http://localhost:3000/api/v1/categories/2
content-type: application/json

{
  "name":"Foods",
  "image": "https://i.pinimg.com/736x/16/65/97/166597a7616100c943ffad09a1f5b9fc.jpg"
}

### DELETE PARA ELIMINAR UNA CATEGORIA POR ID
DELETE http://localhost:3000/api/v1/categories/5

